"""wildfireguardian-osse: an Observing System Simulation Experiment laboratory.

Generates synthetic wildfire worlds whose hidden truth is fully known, together
with imperfect observation streams whose uncertainty, latency, cadence,
missingness and failure modes are explicitly controlled.

    HIDDEN NATURE WORLD  ->  OBSERVATION PROCESS  ->  AVAILABLE OBSERVATIONS

The observation layer never exposes hidden truth directly.  See
``docs/PROJECT_CONTEXT.md`` before using or extending this package.

Synthetic nature model for controlled experiments; not an operational wildfire
forecast model.
"""

__version__ = "0.1.0"

#: Bumped whenever a change alters generated bytes for an unchanged config.
#: Recorded in every world manifest so worlds from different generator
#: behaviours are never silently pooled.
GENERATOR_VERSION = "1.0.0"

MODEL_BANNER = (
    "Synthetic nature model for controlled experiments; "
    "not an operational wildfire forecast model."
)

__all__ = ["__version__", "GENERATOR_VERSION", "MODEL_BANNER"]
